// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Balance defines model for Balance.
type Balance struct {
	Amount int                `json:"amount"`
	UserId openapi_types.UUID `json:"user_id"`
}

// CooldownInfo defines model for CooldownInfo.
type CooldownInfo struct {
	CanHug           bool               `json:"can_hug"`
	CooldownSeconds  int                `json:"cooldown_seconds"`
	GiverId          openapi_types.UUID `json:"giver_id"`
	ReceiverId       openapi_types.UUID `json:"receiver_id"`
	RemainingSeconds int                `json:"remaining_seconds"`
}

// DailyRewardResponse defines model for DailyRewardResponse.
type DailyRewardResponse struct {
	AlreadyClaimed *bool `json:"already_claimed,omitempty"`
	Amount         int   `json:"amount"`
	NewBalance     int   `json:"new_balance"`
	StreakDays     int   `json:"streak_days"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Hug defines model for Hug.
type Hug struct {
	CreatedAt  time.Time          `json:"created_at"`
	GiverId    openapi_types.UUID `json:"giver_id"`
	Id         openapi_types.UUID `json:"id"`
	ReceiverId openapi_types.UUID `json:"receiver_id"`
}

// HugFeedItem defines model for HugFeedItem.
type HugFeedItem struct {
	CreatedAt        time.Time          `json:"created_at"`
	GiverId          openapi_types.UUID `json:"giver_id"`
	GiverUsername    string             `json:"giver_username"`
	Id               openapi_types.UUID `json:"id"`
	ReceiverId       openapi_types.UUID `json:"receiver_id"`
	ReceiverUsername string             `json:"receiver_username"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	HugsGiven    int                `json:"hugs_given"`
	HugsReceived int                `json:"hugs_received"`
	Rank         string             `json:"rank"`
	TotalHugs    int                `json:"total_hugs"`
	UserId       openapi_types.UUID `json:"user_id"`
	Username     string             `json:"username"`
}

// User defines model for User.
type User struct {
	Id       openapi_types.UUID `json:"id"`
	Role     UserRole           `json:"role"`
	Username string             `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserListItem defines model for UserListItem.
type UserListItem struct {
	Id       openapi_types.UUID `json:"id"`
	Role     string             `json:"role"`
	Username string             `json:"username"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Balance      *int               `json:"balance,omitempty"`
	HugsGiven    int                `json:"hugs_given"`
	HugsReceived int                `json:"hugs_received"`
	Id           openapi_types.UUID `json:"id"`
	Rank         string             `json:"rank"`
	Role         string             `json:"role"`
	TotalHugs    int                `json:"total_hugs"`
	Username     string             `json:"username"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterUserJSONBody defines parameters for RegisterUser.
type RegisterUserJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// GetHugsFeedParams defines parameters for GetHugsFeed.
type GetHugsFeedParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody RegisterUserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// admin ping (testing auth)
	// (GET /admin/ping)
	GetAdminPing(ctx echo.Context) error
	// Login
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Register a new user
	// (POST /auth/register)
	RegisterUser(ctx echo.Context) error
	// Get current user balance
	// (GET /balance)
	GetBalance(ctx echo.Context) error
	// Claim daily reward
	// (POST /daily-reward)
	ClaimDailyReward(ctx echo.Context) error
	// Check cooldown status for a user pair
	// (GET /hugs/cooldown/{userId})
	GetCooldown(ctx echo.Context, userId openapi_types.UUID) error
	// Upgrade (reduce) cooldown by spending balance
	// (POST /hugs/cooldown/{userId}/upgrade)
	UpgradeCooldown(ctx echo.Context, userId openapi_types.UUID) error
	// Get recent hugs feed
	// (GET /hugs/feed)
	GetHugsFeed(ctx echo.Context, params GetHugsFeedParams) error
	// Get hug history for current user
	// (GET /hugs/history)
	GetHugHistory(ctx echo.Context) error
	// Send a hug to a user
	// (POST /hugs/{userId})
	SendHug(ctx echo.Context, userId openapi_types.UUID) error
	// Get leaderboard
	// (GET /leaderboard)
	GetLeaderboard(ctx echo.Context, params GetLeaderboardParams) error
	// Ping endpoint
	// (GET /ping)
	GetPing(ctx echo.Context) error
	// Get current user info
	// (GET /users/me)
	GetCurrentUser(ctx echo.Context) error
	// Search users by username
	// (GET /users/search)
	SearchUsers(ctx echo.Context, params SearchUsersParams) error
	// Get user profile with stats
	// (GET /users/{userId}/profile)
	GetUserProfile(ctx echo.Context, userId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdminPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminPing(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminPing(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// GetBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetBalance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBalance(ctx)
	return err
}

// ClaimDailyReward converts echo context to params.
func (w *ServerInterfaceWrapper) ClaimDailyReward(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClaimDailyReward(ctx)
	return err
}

// GetCooldown converts echo context to params.
func (w *ServerInterfaceWrapper) GetCooldown(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCooldown(ctx, userId)
	return err
}

// UpgradeCooldown converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradeCooldown(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpgradeCooldown(ctx, userId)
	return err
}

// GetHugsFeed converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugsFeed(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHugsFeedParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugsFeed(ctx, params)
	return err
}

// GetHugHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugHistory(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugHistory(ctx)
	return err
}

// SendHug converts echo context to params.
func (w *ServerInterfaceWrapper) SendHug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendHug(ctx, userId)
	return err
}

// GetLeaderboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetLeaderboard(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeaderboardParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLeaderboard(ctx, params)
	return err
}

// GetPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPing(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// SearchUsers converts echo context to params.
func (w *ServerInterfaceWrapper) SearchUsers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchUsers(ctx, params)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/admin/ping", wrapper.GetAdminPing)
	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/register", wrapper.RegisterUser)
	router.GET(baseURL+"/balance", wrapper.GetBalance)
	router.POST(baseURL+"/daily-reward", wrapper.ClaimDailyReward)
	router.GET(baseURL+"/hugs/cooldown/:userId", wrapper.GetCooldown)
	router.POST(baseURL+"/hugs/cooldown/:userId/upgrade", wrapper.UpgradeCooldown)
	router.GET(baseURL+"/hugs/feed", wrapper.GetHugsFeed)
	router.GET(baseURL+"/hugs/history", wrapper.GetHugHistory)
	router.POST(baseURL+"/hugs/:userId", wrapper.SendHug)
	router.GET(baseURL+"/leaderboard", wrapper.GetLeaderboard)
	router.GET(baseURL+"/ping", wrapper.GetPing)
	router.GET(baseURL+"/users/me", wrapper.GetCurrentUser)
	router.GET(baseURL+"/users/search", wrapper.SearchUsers)
	router.GET(baseURL+"/users/:userId/profile", wrapper.GetUserProfile)

}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type GetAdminPingRequestObject struct {
}

type GetAdminPingResponseObject interface {
	VisitGetAdminPingResponse(w http.ResponseWriter) error
}

type GetAdminPing200JSONResponse struct {
	Secret string `json:"secret"`
}

func (response GetAdminPing200JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminPing401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAdminPing401JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminPing403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAdminPing403JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse AuthResponse

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse struct{ ConflictJSONResponse }

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetBalanceRequestObject struct {
}

type GetBalanceResponseObject interface {
	VisitGetBalanceResponse(w http.ResponseWriter) error
}

type GetBalance200JSONResponse Balance

func (response GetBalance200JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetBalance401JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyRewardRequestObject struct {
}

type ClaimDailyRewardResponseObject interface {
	VisitClaimDailyRewardResponse(w http.ResponseWriter) error
}

type ClaimDailyReward200JSONResponse DailyRewardResponse

func (response ClaimDailyReward200JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyReward401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ClaimDailyReward401JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyReward429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ClaimDailyReward429JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetCooldownRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type GetCooldownResponseObject interface {
	VisitGetCooldownResponse(w http.ResponseWriter) error
}

type GetCooldown200JSONResponse CooldownInfo

func (response GetCooldown200JSONResponse) VisitGetCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCooldown401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCooldown401JSONResponse) VisitGetCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldownRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type UpgradeCooldownResponseObject interface {
	VisitUpgradeCooldownResponse(w http.ResponseWriter) error
}

type UpgradeCooldown200JSONResponse CooldownInfo

func (response UpgradeCooldown200JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldown400JSONResponse struct{ BadRequestJSONResponse }

func (response UpgradeCooldown400JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldown401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpgradeCooldown401JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHugsFeedRequestObject struct {
	Params GetHugsFeedParams
}

type GetHugsFeedResponseObject interface {
	VisitGetHugsFeedResponse(w http.ResponseWriter) error
}

type GetHugsFeed200JSONResponse []HugFeedItem

func (response GetHugsFeed200JSONResponse) VisitGetHugsFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugsFeed401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugsFeed401JSONResponse) VisitGetHugsFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHugHistoryRequestObject struct {
}

type GetHugHistoryResponseObject interface {
	VisitGetHugHistoryResponse(w http.ResponseWriter) error
}

type GetHugHistory200JSONResponse []Hug

func (response GetHugHistory200JSONResponse) VisitGetHugHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugHistory401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugHistory401JSONResponse) VisitGetHugHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHugRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type SendHugResponseObject interface {
	VisitSendHugResponse(w http.ResponseWriter) error
}

type SendHug201JSONResponse Hug

func (response SendHug201JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SendHug400JSONResponse struct{ BadRequestJSONResponse }

func (response SendHug400JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendHug401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendHug401JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHug404JSONResponse struct{ NotFoundJSONResponse }

func (response SendHug404JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SendHug429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response SendHug429JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboardRequestObject struct {
	Params GetLeaderboardParams
}

type GetLeaderboardResponseObject interface {
	VisitGetLeaderboardResponse(w http.ResponseWriter) error
}

type GetLeaderboard200JSONResponse []LeaderboardEntry

func (response GetLeaderboard200JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboard401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetLeaderboard401JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCurrentUser404JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SearchUsersRequestObject struct {
	Params SearchUsersParams
}

type SearchUsersResponseObject interface {
	VisitSearchUsersResponse(w http.ResponseWriter) error
}

type SearchUsers200JSONResponse []UserListItem

func (response SearchUsers200JSONResponse) VisitSearchUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchUsers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchUsers401JSONResponse) VisitSearchUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfileRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type GetUserProfileResponseObject interface {
	VisitGetUserProfileResponse(w http.ResponseWriter) error
}

type GetUserProfile200JSONResponse UserProfile

func (response GetUserProfile200JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserProfile401JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserProfile404JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// admin ping (testing auth)
	// (GET /admin/ping)
	GetAdminPing(ctx context.Context, request GetAdminPingRequestObject) (GetAdminPingResponseObject, error)
	// Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Register a new user
	// (POST /auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Get current user balance
	// (GET /balance)
	GetBalance(ctx context.Context, request GetBalanceRequestObject) (GetBalanceResponseObject, error)
	// Claim daily reward
	// (POST /daily-reward)
	ClaimDailyReward(ctx context.Context, request ClaimDailyRewardRequestObject) (ClaimDailyRewardResponseObject, error)
	// Check cooldown status for a user pair
	// (GET /hugs/cooldown/{userId})
	GetCooldown(ctx context.Context, request GetCooldownRequestObject) (GetCooldownResponseObject, error)
	// Upgrade (reduce) cooldown by spending balance
	// (POST /hugs/cooldown/{userId}/upgrade)
	UpgradeCooldown(ctx context.Context, request UpgradeCooldownRequestObject) (UpgradeCooldownResponseObject, error)
	// Get recent hugs feed
	// (GET /hugs/feed)
	GetHugsFeed(ctx context.Context, request GetHugsFeedRequestObject) (GetHugsFeedResponseObject, error)
	// Get hug history for current user
	// (GET /hugs/history)
	GetHugHistory(ctx context.Context, request GetHugHistoryRequestObject) (GetHugHistoryResponseObject, error)
	// Send a hug to a user
	// (POST /hugs/{userId})
	SendHug(ctx context.Context, request SendHugRequestObject) (SendHugResponseObject, error)
	// Get leaderboard
	// (GET /leaderboard)
	GetLeaderboard(ctx context.Context, request GetLeaderboardRequestObject) (GetLeaderboardResponseObject, error)
	// Ping endpoint
	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)
	// Get current user info
	// (GET /users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Search users by username
	// (GET /users/search)
	SearchUsers(ctx context.Context, request SearchUsersRequestObject) (SearchUsersResponseObject, error)
	// Get user profile with stats
	// (GET /users/{userId}/profile)
	GetUserProfile(ctx context.Context, request GetUserProfileRequestObject) (GetUserProfileResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAdminPing operation middleware
func (sh *strictHandler) GetAdminPing(ctx echo.Context) error {
	var request GetAdminPingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminPing(ctx.Request().Context(), request.(GetAdminPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAdminPingResponseObject); ok {
		return validResponse.VisitGetAdminPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx echo.Context) error {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx.Request().Context(), request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		return validResponse.VisitRegisterUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBalance operation middleware
func (sh *strictHandler) GetBalance(ctx echo.Context) error {
	var request GetBalanceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBalance(ctx.Request().Context(), request.(GetBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBalance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBalanceResponseObject); ok {
		return validResponse.VisitGetBalanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ClaimDailyReward operation middleware
func (sh *strictHandler) ClaimDailyReward(ctx echo.Context) error {
	var request ClaimDailyRewardRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimDailyReward(ctx.Request().Context(), request.(ClaimDailyRewardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimDailyReward")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ClaimDailyRewardResponseObject); ok {
		return validResponse.VisitClaimDailyRewardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCooldown operation middleware
func (sh *strictHandler) GetCooldown(ctx echo.Context, userId openapi_types.UUID) error {
	var request GetCooldownRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCooldown(ctx.Request().Context(), request.(GetCooldownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCooldown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCooldownResponseObject); ok {
		return validResponse.VisitGetCooldownResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpgradeCooldown operation middleware
func (sh *strictHandler) UpgradeCooldown(ctx echo.Context, userId openapi_types.UUID) error {
	var request UpgradeCooldownRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpgradeCooldown(ctx.Request().Context(), request.(UpgradeCooldownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpgradeCooldown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpgradeCooldownResponseObject); ok {
		return validResponse.VisitUpgradeCooldownResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugsFeed operation middleware
func (sh *strictHandler) GetHugsFeed(ctx echo.Context, params GetHugsFeedParams) error {
	var request GetHugsFeedRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugsFeed(ctx.Request().Context(), request.(GetHugsFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugsFeed")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugsFeedResponseObject); ok {
		return validResponse.VisitGetHugsFeedResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugHistory operation middleware
func (sh *strictHandler) GetHugHistory(ctx echo.Context) error {
	var request GetHugHistoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugHistory(ctx.Request().Context(), request.(GetHugHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugHistoryResponseObject); ok {
		return validResponse.VisitGetHugHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SendHug operation middleware
func (sh *strictHandler) SendHug(ctx echo.Context, userId openapi_types.UUID) error {
	var request SendHugRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendHug(ctx.Request().Context(), request.(SendHugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendHug")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SendHugResponseObject); ok {
		return validResponse.VisitSendHugResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLeaderboard operation middleware
func (sh *strictHandler) GetLeaderboard(ctx echo.Context, params GetLeaderboardParams) error {
	var request GetLeaderboardRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLeaderboard(ctx.Request().Context(), request.(GetLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLeaderboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLeaderboardResponseObject); ok {
		return validResponse.VisitGetLeaderboardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(ctx echo.Context) error {
	var request GetPingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx.Request().Context(), request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		return validResponse.VisitGetPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx echo.Context) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.Request().Context(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		return validResponse.VisitGetCurrentUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchUsers operation middleware
func (sh *strictHandler) SearchUsers(ctx echo.Context, params SearchUsersParams) error {
	var request SearchUsersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchUsers(ctx.Request().Context(), request.(SearchUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchUsersResponseObject); ok {
		return validResponse.VisitSearchUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserProfile operation middleware
func (sh *strictHandler) GetUserProfile(ctx echo.Context, userId openapi_types.UUID) error {
	var request GetUserProfileRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserProfile(ctx.Request().Context(), request.(GetUserProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserProfileResponseObject); ok {
		return validResponse.VisitGetUserProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RaUW/bug7+K4LufdgAr0633Yebt6133XqxMxTtivMwFIFqMbFWW3IluUVOkf9+QMmO",
	"7URO0qRJcba3uJZE8uNHiqT7SBOVF0qCtIYOH6kGUyhpwD18ZPwC7kowFp8SJS1I95MVRSYSZoWS8U+j",
	"JP7NJCnkDH/9W8OYDum/4ubo2L818Setlaaz2SyiHEyiRYGH0CHKIrWwWURPlBxnIjmA4KSWNIvoqdI3",
	"gnOQ+xc7nouaRfSbsqeqlHz/Yr8pS7yoWUS/K/UHk9MKdrN/6RfMAslELiyJSaJUxtWDJCyx4h5QoSvJ",
	"SpsqLf6CA2DRkYavqx144IfSphdVLOBzoVUB2gofGFbdeo7YaQF0SI3VQk7QgtKAXqfQFa5BeRruSqHR",
	"1B/VkdUB11F9srr5CZ6bH1nGZBJQhuWq9BhVe4S0MEER/rSRcFiOlc6ZpUNaloLTaFH1BXXqjVF9fEil",
	"k8qDZ3KslvVKmByl5aSl2I1SGTDH+Nr5IwOJktyE1Z+I+031R/UTeNr6nAkp5GSVDguwzBXqigvYEzo/",
	"mmMSQvN/TGTTC3hgmvczj2UaGJ+OkoyJ3AfJMrirGCHhYXTTUGl5gbEa2O2Is+kmgFSiutu6UkK2+phc",
	"poziEAyrHIxhk9C7BX3cCc36kOwvnpMLkjUwC3zEbIc7nFl4Y0UOIQI9iZ17IfGC8W5JP0UbE3tgOQXg",
	"ZxbyF4DHL8asI1ke5sDe0kC1foXwJ+G8YEpIwlpnfAXGQd8opvknafV02SNpOTEjFCXDYezeV5J5eIlm",
	"8jaItFWWZZinzK63il+7GarNldPCqaVK1LZ50cDKmhCWV9WV3MVvU3aozKkOssxrJfFS5LmQLWnb2Lto",
	"qhPVZ8BXYWw4NJ9oyKEUPtdqLLLADbby8nkGVm+KRx/5e4HaJCp2AHINvTuB0MN1vL0hKbWw00usNasu",
	"DpgGjQWtg989ndbw/P/P77QqfF0R4d42eKXWFr50FlWN1y2hzzNmEWoyVpqk5WQi5IQom4ImaJ8hD8Km",
	"RM/LfhORyv8RYZITNAQNssIi6ngJGcIMYeQS9L1IgHw4P6MRvQdtvMTjo8HRAOFWBUhWCDqk744GR+9o",
	"RAtmU2dx7MIzLhD74SOdgLu1kISufzjjdEg/g/2Aq85xUdTte98OBk/qProEN5BosOtZUK0LuHGpU0Ew",
	"QBNhCMuqVun94Livz5jbEnc7HNz0bv2mpgluE4oOf3Sp9KNOgrPriJoyzxleU/6PBKEnrywYiz9Qidfu",
	"tBh/xpmaCAdhoUzANV/daw8WGPtR8ekO7iiYMQ9K8x2TXytc5yeGXdfssrqE2Y7cWtVIdprUAG0ckMSU",
	"SQLGjMvMU2CwngKtwc92VJu1KeH92bhfw0QYW13KQQZcVCuu/G37ixLh+GBEQBxJDTvwFiWy6dak+O/6",
	"LfMpXpcQtXsJIxIe3E3h6dGqDfqSdj0G2WNY1SL6gKy13D40+nNqt77sptbPYElSag3SOswaRRA7zkQ2",
	"faPd/KA/sk4yJvLWpGGfOIYGGgFM3TLiFSf1XGPrG+7tBrRcnHvu4BOHJ+EtE7w3sFCL66FQ/IhHnPHZ",
	"KmLXwzSXVzTLwYI2Thu8K11xQyPqcxT159HFHBO1PLNudHC9R893BoMBl9fviasqDx1HJykkt8342Vhm",
	"S+MqWObjqmBCr3JjXBYTzfyoKhxmV37Bb+nTChx+2GpjOypUfiKvNPAygdcNK26mxBQgOdavnTzrKDEG",
	"3372BTP2MafgGreQ4+9K0NPG8641om1HcxizMrN0+J9BtDyC3dXNwkJu1vm7PQ+czZVgWrNp8NMOJHgv",
	"ITrEofMSt6NeUmLusVQYq/wgbYXTvlSrDgTwJsB+KSekVv4lME0b+S5HtiuQFr7tKy6cEy9BcrT5xXLh",
	"89XbznVhVxnE5lnq6636+/frN80/Nr9AuYQcIMxxyqrquvUkypqJ96oYbQ3Gd86tb0O5NQofo8ZjAz3n",
	"vFiKXvpKsEE6ae0hIK3G5vgl0krb344AC9O6xdvFlloawogReZEBqZVCGiWunhNjYlMgZmFUFi1zaA8j",
	"P1dCbjDy8+u2Gvl1Omg0gYDkhRLSd9exm7fG+crm+cTn7vlYZU+lYvUPDsslYrt53aH0f3Kie8ae26vd",
	"AG6A6STtBf3SvUZAzGb56q6TY5bo9Psluc7Xr00SnDCWqDHJmU1SDBPnp4PnOO/46ivIzZTMx4Yt7sz7",
	"yaL5WNYXuu1var9AN9k2p2/OVqHivyFh6jT/jHxR9invz8W87t1W6owOacwKEd8f09n17O8AAAD//xtz",
	"dgWOKQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
