// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	CANNOTHUGSELF       ErrorCode = "CANNOT_HUG_SELF"
	COOLDOWNACTIVE      ErrorCode = "COOLDOWN_ACTIVE"
	INSUFFICIENTBALANCE ErrorCode = "INSUFFICIENT_BALANCE"
	INVALIDCREDENTIALS  ErrorCode = "INVALID_CREDENTIALS"
	USERALREADYEXISTS   ErrorCode = "USER_ALREADY_EXISTS"
	USERNOTFOUND        ErrorCode = "USER_NOT_FOUND"
	WEAKPASSWORD        ErrorCode = "WEAK_PASSWORD"
	WRONGPASSWORD       ErrorCode = "WRONG_PASSWORD"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Balance defines model for Balance.
type Balance struct {
	Amount int                `json:"amount"`
	UserId openapi_types.UUID `json:"user_id"`
}

// CooldownInfo defines model for CooldownInfo.
type CooldownInfo struct {
	CanHug           bool               `json:"can_hug"`
	CooldownSeconds  int                `json:"cooldown_seconds"`
	GiverId          openapi_types.UUID `json:"giver_id"`
	ReceiverId       openapi_types.UUID `json:"receiver_id"`
	RemainingSeconds int                `json:"remaining_seconds"`
}

// DailyRewardResponse defines model for DailyRewardResponse.
type DailyRewardResponse struct {
	AlreadyClaimed *bool `json:"already_claimed,omitempty"`
	Amount         int   `json:"amount"`
	NewBalance     int   `json:"new_balance"`
	StreakDays     int   `json:"streak_days"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Gender defines model for Gender.
type Gender string

// Hug defines model for Hug.
type Hug struct {
	CreatedAt  time.Time          `json:"created_at"`
	GiverId    openapi_types.UUID `json:"giver_id"`
	Id         openapi_types.UUID `json:"id"`
	ReceiverId openapi_types.UUID `json:"receiver_id"`
}

// HugActivityItem defines model for HugActivityItem.
type HugActivityItem struct {
	Count     int       `json:"count"`
	Timestamp time.Time `json:"timestamp"`
}

// HugFeedItem defines model for HugFeedItem.
type HugFeedItem struct {
	CreatedAt        time.Time          `json:"created_at"`
	GiverGender      *Gender            `json:"giver_gender,omitempty"`
	GiverId          openapi_types.UUID `json:"giver_id"`
	GiverUsername    string             `json:"giver_username"`
	Id               openapi_types.UUID `json:"id"`
	ReceiverId       openapi_types.UUID `json:"receiver_id"`
	ReceiverUsername string             `json:"receiver_username"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	HugsGiven    int                `json:"hugs_given"`
	HugsReceived int                `json:"hugs_received"`
	Rank         string             `json:"rank"`
	TotalHugs    int                `json:"total_hugs"`
	UserId       openapi_types.UUID `json:"user_id"`
	Username     string             `json:"username"`
}

// User defines model for User.
type User struct {
	Gender   *Gender            `json:"gender,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Role     UserRole           `json:"role"`
	Username string             `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserListItem defines model for UserListItem.
type UserListItem struct {
	Gender   *Gender            `json:"gender,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Role     string             `json:"role"`
	Username string             `json:"username"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Balance      *int               `json:"balance,omitempty"`
	Gender       *Gender            `json:"gender,omitempty"`
	HugsGiven    int                `json:"hugs_given"`
	HugsReceived int                `json:"hugs_received"`
	Id           openapi_types.UUID `json:"id"`
	Rank         string             `json:"rank"`
	Role         string             `json:"role"`
	TotalHugs    int                `json:"total_hugs"`
	Username     string             `json:"username"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RefreshTokenParams defines parameters for RefreshToken.
type RefreshTokenParams struct {
	RefreshToken string `form:"refresh_token" json:"refresh_token"`
}

// RegisterUserJSONBody defines parameters for RegisterUser.
type RegisterUserJSONBody struct {
	Gender *Gender `json:"gender,omitempty"`

	// Password Password must be 8-128 characters, contain at least one letter, one digit, and one special character
	Password string `json:"password"`

	// Username Username must be 3-32 characters, start with a letter, and contain only letters, numbers, and underscores
	Username string `json:"username"`
}

// GetHugsFeedParams defines parameters for GetHugsFeed.
type GetHugsFeedParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ChangePasswordJSONBody defines parameters for ChangePassword.
type ChangePasswordJSONBody struct {
	// NewPassword Password must be 8-128 characters, contain at least one letter, one digit, and one special character
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// UpdateUserSettingsJSONBody defines parameters for UpdateUserSettings.
type UpdateUserSettingsJSONBody struct {
	Gender *Gender `json:"gender,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody RegisterUserJSONBody

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody ChangePasswordJSONBody

// UpdateUserSettingsJSONRequestBody defines body for UpdateUserSettings for application/json ContentType.
type UpdateUserSettingsJSONRequestBody UpdateUserSettingsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// admin ping (testing auth)
	// (GET /admin/ping)
	GetAdminPing(ctx echo.Context) error
	// Login
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Logout and clear refresh token cookie
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Refresh access token using refresh token cookie
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context, params RefreshTokenParams) error
	// Register a new user
	// (POST /auth/register)
	RegisterUser(ctx echo.Context) error
	// Get current user balance
	// (GET /balance)
	GetBalance(ctx echo.Context) error
	// Claim daily reward
	// (POST /daily-reward)
	ClaimDailyReward(ctx echo.Context) error
	// Get hug activity for the last 24 hours grouped by hour
	// (GET /hugs/activity)
	GetHugActivity(ctx echo.Context) error
	// Check cooldown status for a user pair
	// (GET /hugs/cooldown/{userId})
	GetCooldown(ctx echo.Context, userId openapi_types.UUID) error
	// Upgrade (reduce) cooldown by spending balance
	// (POST /hugs/cooldown/{userId}/upgrade)
	UpgradeCooldown(ctx echo.Context, userId openapi_types.UUID) error
	// Get recent hugs feed
	// (GET /hugs/feed)
	GetHugsFeed(ctx echo.Context, params GetHugsFeedParams) error
	// Get hug history for current user
	// (GET /hugs/history)
	GetHugHistory(ctx echo.Context) error
	// Send a hug to a user
	// (POST /hugs/{userId})
	SendHug(ctx echo.Context, userId openapi_types.UUID) error
	// Get leaderboard
	// (GET /leaderboard)
	GetLeaderboard(ctx echo.Context, params GetLeaderboardParams) error
	// Ping endpoint
	// (GET /ping)
	GetPing(ctx echo.Context) error
	// Get current user info
	// (GET /users/me)
	GetCurrentUser(ctx echo.Context) error
	// Change current user password
	// (PUT /users/me/password)
	ChangePassword(ctx echo.Context) error
	// Update current user settings
	// (PUT /users/me/settings)
	UpdateUserSettings(ctx echo.Context) error
	// Search users by username
	// (GET /users/search)
	SearchUsers(ctx echo.Context, params SearchUsersParams) error
	// Get user profile with stats
	// (GET /users/{userId}/profile)
	GetUserProfile(ctx echo.Context, userId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdminPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminPing(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminPing(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshTokenParams

	if cookie, err := ctx.Cookie("refresh_token"); err == nil {

		var value string
		err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refresh_token: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refresh_token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx, params)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// GetBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetBalance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBalance(ctx)
	return err
}

// ClaimDailyReward converts echo context to params.
func (w *ServerInterfaceWrapper) ClaimDailyReward(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClaimDailyReward(ctx)
	return err
}

// GetHugActivity converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugActivity(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugActivity(ctx)
	return err
}

// GetCooldown converts echo context to params.
func (w *ServerInterfaceWrapper) GetCooldown(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCooldown(ctx, userId)
	return err
}

// UpgradeCooldown converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradeCooldown(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpgradeCooldown(ctx, userId)
	return err
}

// GetHugsFeed converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugsFeed(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHugsFeedParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugsFeed(ctx, params)
	return err
}

// GetHugHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugHistory(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugHistory(ctx)
	return err
}

// SendHug converts echo context to params.
func (w *ServerInterfaceWrapper) SendHug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendHug(ctx, userId)
	return err
}

// GetLeaderboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetLeaderboard(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeaderboardParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLeaderboard(ctx, params)
	return err
}

// GetPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPing(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// ChangePassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangePassword(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangePassword(ctx)
	return err
}

// UpdateUserSettings converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserSettings(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserSettings(ctx)
	return err
}

// SearchUsers converts echo context to params.
func (w *ServerInterfaceWrapper) SearchUsers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchUsers(ctx, params)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/admin/ping", wrapper.GetAdminPing)
	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/logout", wrapper.Logout)
	router.POST(baseURL+"/auth/refresh", wrapper.RefreshToken)
	router.POST(baseURL+"/auth/register", wrapper.RegisterUser)
	router.GET(baseURL+"/balance", wrapper.GetBalance)
	router.POST(baseURL+"/daily-reward", wrapper.ClaimDailyReward)
	router.GET(baseURL+"/hugs/activity", wrapper.GetHugActivity)
	router.GET(baseURL+"/hugs/cooldown/:userId", wrapper.GetCooldown)
	router.POST(baseURL+"/hugs/cooldown/:userId/upgrade", wrapper.UpgradeCooldown)
	router.GET(baseURL+"/hugs/feed", wrapper.GetHugsFeed)
	router.GET(baseURL+"/hugs/history", wrapper.GetHugHistory)
	router.POST(baseURL+"/hugs/:userId", wrapper.SendHug)
	router.GET(baseURL+"/leaderboard", wrapper.GetLeaderboard)
	router.GET(baseURL+"/ping", wrapper.GetPing)
	router.GET(baseURL+"/users/me", wrapper.GetCurrentUser)
	router.PUT(baseURL+"/users/me/password", wrapper.ChangePassword)
	router.PUT(baseURL+"/users/me/settings", wrapper.UpdateUserSettings)
	router.GET(baseURL+"/users/search", wrapper.SearchUsers)
	router.GET(baseURL+"/users/:userId/profile", wrapper.GetUserProfile)

}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type GetAdminPingRequestObject struct {
}

type GetAdminPingResponseObject interface {
	VisitGetAdminPingResponse(w http.ResponseWriter) error
}

type GetAdminPing200JSONResponse struct {
	Secret string `json:"secret"`
}

func (response GetAdminPing200JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminPing401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAdminPing401JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminPing403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAdminPing403JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    AuthResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200ResponseHeaders struct {
	SetCookie string
}

type Logout200JSONResponse struct {
	Body struct {
		Message string `json:"message"`
	}
	Headers Logout200ResponseHeaders
}

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshTokenRequestObject struct {
	Params RefreshTokenParams
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200ResponseHeaders struct {
	SetCookie string
}

type RefreshToken200JSONResponse struct {
	Body struct {
		Token string `json:"token"`
	}
	Headers RefreshToken200ResponseHeaders
}

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201ResponseHeaders struct {
	SetCookie string
}

type RegisterUser201JSONResponse struct {
	Body    AuthResponse
	Headers RegisterUser201ResponseHeaders
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse struct{ ConflictJSONResponse }

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetBalanceRequestObject struct {
}

type GetBalanceResponseObject interface {
	VisitGetBalanceResponse(w http.ResponseWriter) error
}

type GetBalance200JSONResponse Balance

func (response GetBalance200JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetBalance401JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyRewardRequestObject struct {
}

type ClaimDailyRewardResponseObject interface {
	VisitClaimDailyRewardResponse(w http.ResponseWriter) error
}

type ClaimDailyReward200JSONResponse DailyRewardResponse

func (response ClaimDailyReward200JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyReward401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ClaimDailyReward401JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyReward429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ClaimDailyReward429JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetHugActivityRequestObject struct {
}

type GetHugActivityResponseObject interface {
	VisitGetHugActivityResponse(w http.ResponseWriter) error
}

type GetHugActivity200JSONResponse []HugActivityItem

func (response GetHugActivity200JSONResponse) VisitGetHugActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugActivity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugActivity401JSONResponse) VisitGetHugActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCooldownRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type GetCooldownResponseObject interface {
	VisitGetCooldownResponse(w http.ResponseWriter) error
}

type GetCooldown200JSONResponse CooldownInfo

func (response GetCooldown200JSONResponse) VisitGetCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCooldown401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCooldown401JSONResponse) VisitGetCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldownRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type UpgradeCooldownResponseObject interface {
	VisitUpgradeCooldownResponse(w http.ResponseWriter) error
}

type UpgradeCooldown200JSONResponse CooldownInfo

func (response UpgradeCooldown200JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldown400JSONResponse struct{ BadRequestJSONResponse }

func (response UpgradeCooldown400JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldown401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpgradeCooldown401JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHugsFeedRequestObject struct {
	Params GetHugsFeedParams
}

type GetHugsFeedResponseObject interface {
	VisitGetHugsFeedResponse(w http.ResponseWriter) error
}

type GetHugsFeed200JSONResponse []HugFeedItem

func (response GetHugsFeed200JSONResponse) VisitGetHugsFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugsFeed401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugsFeed401JSONResponse) VisitGetHugsFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHugHistoryRequestObject struct {
}

type GetHugHistoryResponseObject interface {
	VisitGetHugHistoryResponse(w http.ResponseWriter) error
}

type GetHugHistory200JSONResponse []HugFeedItem

func (response GetHugHistory200JSONResponse) VisitGetHugHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugHistory401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugHistory401JSONResponse) VisitGetHugHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHugRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type SendHugResponseObject interface {
	VisitSendHugResponse(w http.ResponseWriter) error
}

type SendHug201JSONResponse Hug

func (response SendHug201JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SendHug400JSONResponse struct{ BadRequestJSONResponse }

func (response SendHug400JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendHug401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendHug401JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHug404JSONResponse struct{ NotFoundJSONResponse }

func (response SendHug404JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SendHug429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response SendHug429JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboardRequestObject struct {
	Params GetLeaderboardParams
}

type GetLeaderboardResponseObject interface {
	VisitGetLeaderboardResponse(w http.ResponseWriter) error
}

type GetLeaderboard200JSONResponse []LeaderboardEntry

func (response GetLeaderboard200JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboard401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetLeaderboard401JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCurrentUser404JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword200JSONResponse struct {
	Message string `json:"message"`
}

func (response ChangePassword200JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword400JSONResponse struct{ BadRequestJSONResponse }

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ChangePassword401JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSettingsRequestObject struct {
	Body *UpdateUserSettingsJSONRequestBody
}

type UpdateUserSettingsResponseObject interface {
	VisitUpdateUserSettingsResponse(w http.ResponseWriter) error
}

type UpdateUserSettings200JSONResponse User

func (response UpdateUserSettings200JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSettings400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUserSettings400JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSettings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUserSettings401JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SearchUsersRequestObject struct {
	Params SearchUsersParams
}

type SearchUsersResponseObject interface {
	VisitSearchUsersResponse(w http.ResponseWriter) error
}

type SearchUsers200JSONResponse []UserListItem

func (response SearchUsers200JSONResponse) VisitSearchUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchUsers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchUsers401JSONResponse) VisitSearchUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfileRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type GetUserProfileResponseObject interface {
	VisitGetUserProfileResponse(w http.ResponseWriter) error
}

type GetUserProfile200JSONResponse UserProfile

func (response GetUserProfile200JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserProfile401JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserProfile404JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// admin ping (testing auth)
	// (GET /admin/ping)
	GetAdminPing(ctx context.Context, request GetAdminPingRequestObject) (GetAdminPingResponseObject, error)
	// Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout and clear refresh token cookie
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh access token using refresh token cookie
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register a new user
	// (POST /auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Get current user balance
	// (GET /balance)
	GetBalance(ctx context.Context, request GetBalanceRequestObject) (GetBalanceResponseObject, error)
	// Claim daily reward
	// (POST /daily-reward)
	ClaimDailyReward(ctx context.Context, request ClaimDailyRewardRequestObject) (ClaimDailyRewardResponseObject, error)
	// Get hug activity for the last 24 hours grouped by hour
	// (GET /hugs/activity)
	GetHugActivity(ctx context.Context, request GetHugActivityRequestObject) (GetHugActivityResponseObject, error)
	// Check cooldown status for a user pair
	// (GET /hugs/cooldown/{userId})
	GetCooldown(ctx context.Context, request GetCooldownRequestObject) (GetCooldownResponseObject, error)
	// Upgrade (reduce) cooldown by spending balance
	// (POST /hugs/cooldown/{userId}/upgrade)
	UpgradeCooldown(ctx context.Context, request UpgradeCooldownRequestObject) (UpgradeCooldownResponseObject, error)
	// Get recent hugs feed
	// (GET /hugs/feed)
	GetHugsFeed(ctx context.Context, request GetHugsFeedRequestObject) (GetHugsFeedResponseObject, error)
	// Get hug history for current user
	// (GET /hugs/history)
	GetHugHistory(ctx context.Context, request GetHugHistoryRequestObject) (GetHugHistoryResponseObject, error)
	// Send a hug to a user
	// (POST /hugs/{userId})
	SendHug(ctx context.Context, request SendHugRequestObject) (SendHugResponseObject, error)
	// Get leaderboard
	// (GET /leaderboard)
	GetLeaderboard(ctx context.Context, request GetLeaderboardRequestObject) (GetLeaderboardResponseObject, error)
	// Ping endpoint
	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)
	// Get current user info
	// (GET /users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Change current user password
	// (PUT /users/me/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// Update current user settings
	// (PUT /users/me/settings)
	UpdateUserSettings(ctx context.Context, request UpdateUserSettingsRequestObject) (UpdateUserSettingsResponseObject, error)
	// Search users by username
	// (GET /users/search)
	SearchUsers(ctx context.Context, request SearchUsersRequestObject) (SearchUsersResponseObject, error)
	// Get user profile with stats
	// (GET /users/{userId}/profile)
	GetUserProfile(ctx context.Context, request GetUserProfileRequestObject) (GetUserProfileResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAdminPing operation middleware
func (sh *strictHandler) GetAdminPing(ctx echo.Context) error {
	var request GetAdminPingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminPing(ctx.Request().Context(), request.(GetAdminPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAdminPingResponseObject); ok {
		return validResponse.VisitGetAdminPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx echo.Context, params RefreshTokenParams) error {
	var request RefreshTokenRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx echo.Context) error {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx.Request().Context(), request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		return validResponse.VisitRegisterUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBalance operation middleware
func (sh *strictHandler) GetBalance(ctx echo.Context) error {
	var request GetBalanceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBalance(ctx.Request().Context(), request.(GetBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBalance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBalanceResponseObject); ok {
		return validResponse.VisitGetBalanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ClaimDailyReward operation middleware
func (sh *strictHandler) ClaimDailyReward(ctx echo.Context) error {
	var request ClaimDailyRewardRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimDailyReward(ctx.Request().Context(), request.(ClaimDailyRewardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimDailyReward")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ClaimDailyRewardResponseObject); ok {
		return validResponse.VisitClaimDailyRewardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugActivity operation middleware
func (sh *strictHandler) GetHugActivity(ctx echo.Context) error {
	var request GetHugActivityRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugActivity(ctx.Request().Context(), request.(GetHugActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugActivity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugActivityResponseObject); ok {
		return validResponse.VisitGetHugActivityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCooldown operation middleware
func (sh *strictHandler) GetCooldown(ctx echo.Context, userId openapi_types.UUID) error {
	var request GetCooldownRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCooldown(ctx.Request().Context(), request.(GetCooldownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCooldown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCooldownResponseObject); ok {
		return validResponse.VisitGetCooldownResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpgradeCooldown operation middleware
func (sh *strictHandler) UpgradeCooldown(ctx echo.Context, userId openapi_types.UUID) error {
	var request UpgradeCooldownRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpgradeCooldown(ctx.Request().Context(), request.(UpgradeCooldownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpgradeCooldown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpgradeCooldownResponseObject); ok {
		return validResponse.VisitUpgradeCooldownResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugsFeed operation middleware
func (sh *strictHandler) GetHugsFeed(ctx echo.Context, params GetHugsFeedParams) error {
	var request GetHugsFeedRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugsFeed(ctx.Request().Context(), request.(GetHugsFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugsFeed")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugsFeedResponseObject); ok {
		return validResponse.VisitGetHugsFeedResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugHistory operation middleware
func (sh *strictHandler) GetHugHistory(ctx echo.Context) error {
	var request GetHugHistoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugHistory(ctx.Request().Context(), request.(GetHugHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugHistoryResponseObject); ok {
		return validResponse.VisitGetHugHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SendHug operation middleware
func (sh *strictHandler) SendHug(ctx echo.Context, userId openapi_types.UUID) error {
	var request SendHugRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendHug(ctx.Request().Context(), request.(SendHugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendHug")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SendHugResponseObject); ok {
		return validResponse.VisitSendHugResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLeaderboard operation middleware
func (sh *strictHandler) GetLeaderboard(ctx echo.Context, params GetLeaderboardParams) error {
	var request GetLeaderboardRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLeaderboard(ctx.Request().Context(), request.(GetLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLeaderboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLeaderboardResponseObject); ok {
		return validResponse.VisitGetLeaderboardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(ctx echo.Context) error {
	var request GetPingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx.Request().Context(), request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		return validResponse.VisitGetPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx echo.Context) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.Request().Context(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		return validResponse.VisitGetCurrentUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(ctx echo.Context) error {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx.Request().Context(), request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		return validResponse.VisitChangePasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserSettings operation middleware
func (sh *strictHandler) UpdateUserSettings(ctx echo.Context) error {
	var request UpdateUserSettingsRequestObject

	var body UpdateUserSettingsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserSettings(ctx.Request().Context(), request.(UpdateUserSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserSettings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserSettingsResponseObject); ok {
		return validResponse.VisitUpdateUserSettingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchUsers operation middleware
func (sh *strictHandler) SearchUsers(ctx echo.Context, params SearchUsersParams) error {
	var request SearchUsersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchUsers(ctx.Request().Context(), request.(SearchUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchUsersResponseObject); ok {
		return validResponse.VisitSearchUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserProfile operation middleware
func (sh *strictHandler) GetUserProfile(ctx echo.Context, userId openapi_types.UUID) error {
	var request GetUserProfileRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserProfile(ctx.Request().Context(), request.(GetUserProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserProfileResponseObject); ok {
		return validResponse.VisitGetUserProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaa1fjyNH+K3363Q+77xHYwCRnlm8eA4MTYjg27CSZEJ9GKsu9I3Vr+jLEO8f/Pacv",
	"kiVZ8gUGs5PkExbqS9VTT1VXV+krDnmacQZMSXz6FQuQGWcS7MM7Eo3gswapzFPImQJmf5IsS2hIFOWs",
	"86vkzPxPhjNIifn1g4ApPsX/11ku3XFvZedcCC7wYrEIcAQyFDQzi+BTsxfKN1sEuM/ZNKHhHjYO850W",
	"Ab7g4oFGEbCX33ZabLUI8JCrC65Z9PLbDrlCbqtFgG85/wthcw+7fPndR0QBSmhKFeqgkPMk4o8MkVDR",
	"L2AEumNEqxkX9DfYAxaV3cxrP8Ms2NNqNvK+YJ4zwTMQijrHUPyT44iaZ4BPsVSCsthooCWITQLdmTFm",
	"PwGfNRVG1Y9+Sb/AfZCvzB9+BcfNdyQhLGwQhqRcO4z8HMoUxGYLt9qEWiynXKRE4VOsNY1wUBe9Jk4+",
	"MciXbxKp7y04YFO+KldI2GSm45JgD5wnQCzjc+NPJIScRbJZ/Jh+2VZ+I34Iu41PCWWUxetkqMFSCFTd",
	"rkGfpvWDApMmNM8ITeYjeCQiamceSQSQaD4JE0JT5ySr4K5jBIPHycOSSqsDpBJAPk0iMt8GEL9VdVp1",
	"lyZdnU+uUoZHsJU7983ARYBTkJLE0OCKNTntysvxrTL1vQTAdGrmfTjv/Xly0xuPP1yPznCA78bno0nv",
	"anTeO/vb5Pyvg/HtGAd4MPyldzU4m/RH52fnw9tB72qcjx1e304uru+GZnK/NzSPl3fvJ+Pzqwvzn+vr",
	"q7PrD8NJr387+OXcLjW+u7gY9Afnw9vJu95Vb9g3//4wuh6+Xwpy38Dn98AiF3xy4VOSGKWnYH80zbl0",
	"/lmzggCiIJoQVfGjiCg4UDSFJmfayVNfxKFrBrdD2t11qWITFS513DOHElXzgYK0iaitDmYQkoqk2bbg",
	"1Q+CYn7gt2mR8AIgapHuyQaMCw6tc0HPtF3N7gabk4WRFBqPzxcL9X78ms134k9NlaYdNpLsCkgE4oET",
	"EZ0zJeardpzpWE7MVqyZava93zlqHiII+9SItOKKJOYsks/NHNzY7VBdphUlnEqiBGWd6wp6bZqwvPNp",
	"VxW/Xdm8LZt4UjkjbMoWYBKllDVG2R1ZV6YVT6BV4SsqVXMAeGHF96XgjeBTmjRkQWsTmF2V/wZeti1+",
	"bc7YCuw2XvoM4De4W8UxW3zPZIwQakHVfGyg9ZUDIAKEuURZc9mnixyeP324xf6yZRNX+3aJ10ypzF3X",
	"qL9XVK9tNwlRBmo05QLNdBxTFiOuZiCQ0U+iR6pmSBRXTRkgz5cAERYho4hRSFFlUDdHqUREIoLGIL7Q",
	"EFDvZoAD/AWEdDseHXYPuwZungEjGcWn+OSwe3iCA5wRNbMad6z7dzKDvfVAe/Ya0to76yDCp/g9qJ4Z",
	"dWMGBdVay3G3u9ONt+oQEkIBajML/LgGM67cjg0YIBCViCT+ev6me9TmVoUuneqt2kw62TxpWXgpEwqf",
	"fqxS6WMeZBf3AZY6TYk5Nt0/kYEe/ahAKvPDCPGTXa1jfnYSHlMLYcZlg2mu7GsHFkj1jkfzncxBooia",
	"VyS5KRlmShIJQc1WGZHykQsbMlLyrytgsdHt6PhtgFPKiucNB0lp6snxhpkNp7APA4UwzZRYzlJCw+KZ",
	"nF0XjysFlwY6WgMhqcMQpJzqxIQrm0BZScagDvqcf6KwGi9GMBUgZ8hWWFDoRgUlsepgLSxru5tZW6qP",
	"Ps07FmUWOwpWGMu1KlO2qlc/ASIkUjNAl0pl1yyZI+F0nZR1PcTBKtnNyt80Am19E2+/gjcaPYYIca1K",
	"lk/m29veYpSjsgsD6pYxIpjDI2xfcGk5/7rddHcStjAcUhxRKTUgghg8ImIRcJseoiFHPU8layHkIEE5",
	"1of/YCuG965w62uNGREkBWVx/PgVU1cO9+i4OIMrguF6RFgH4v035VdbybWxjLoNt4Y1RB3U0Q5xhStz",
	"vXsKu54fLPKgVtFAS3PybSRnTKXy16XGs3DkR9y5e80ejsRdU/byEVpLDv0blGqp0AOgtwdHx29ROCOC",
	"hIbpATIKEMoQUSgBIhXiDFACSoEI7O+IxlS5XNE8ygxCSpLlGjhYd26/3XBur0QC+6aQ9+Tg5LgirlRE",
	"KJfTkkJMG4q8HtzED/dCBojp9MH+MEO0AUyGXICsCl3LGE5sIqtAGJH++ZEc/NY7+Pu9/9s9+Hly//8/",
	"4P1lFUd7yyoM/Cj3CIieeMrsL8P4efOUonNaDxhOSX+W6LwH1SndpdsuLXnr6QXTv3yLNhvlUj49dLbf",
	"Kar1m+rV4j0oFGohgCmL2VIQg11EaDI/ELZn0x5P+wmhaam785I4NjWRGjC1w5ATHOW9pCff8I63oGW9",
	"1/wMm1g8UVRSwVljpmPZIb5uv47PpfL+c21BFaRyk1Hq7YRFERWJEGTeZKBLrkUyRzMdI9sEkLbaYVLG",
	"xBxZx2/QjGshX8UfjFA5zM1ioVhwnUGEHub2HyX75I3SzlezzSBarDNU3mBuyVUzombLTNWttzZF3dRC",
	"un9Bz6w0yxssnr9Htuq1b7v2ZxB+Wn6SIRVR2nGOuLiXEbrWjB2dxYK45mlzGLxzA/4rberB8TF2X6WF",
	"p1HB2wn9KCDSIfy0ZMXD3CTDLDK3jMo5aCkxBVceXxN15QXYG1aT4T9rEPOl5W3ptpJERTAlOlH49A9d",
	"m8vSVKf49KjbtamsfwpWP1i431OIL/qxW4T3EYQmozC4IYvba8RxsSJEYcsZlYqLTYfopR/1OwT4Usco",
	"V+K1zki/v42i5RyyhHP5EGyOmmNg0aWOXy9afrvLmFGjxVTSYFO5fO0tUJpJbzZPKj7RfIWE13AAEcsp",
	"xf2B7EiULL8hWOerpU8Nnh19j3eLvkHzBnw6ldCyQ3nJ7msF9JWvM7YIOqU5CJgSFF4nQS+zwtKk1pWs",
	"n0VKCyYRQZKmWQIoF8qQLbR5IZ3aHF/WWoLBKtNeoLVpU9EtWptu3JNam5VKiVEBAYsyTpmronRsX7mT",
	"ri2S9F2EL4qmL5Ry+o+HV1PNcpHiGVeIncPhN6ytOLHLgHfKld5MNxVXZoTFkJd991OuZvA4+d5K0DyJ",
	"Jk/uPNdcrbJWUIVjH33kPXQeCyOGll/fxcXNuULVpQq7VN1KglKUua+KGt3qLouIAhNsxvnQ32EnaPHK",
	"Hy20BeMcM6QtjN/Jtd+IWmVPQZMSeyQQEc5aT8KxfW2Akdulmp8rSWApLP3xTUMc+l+62s7E4nvQbVJV",
	"ak6dKUqJCmcm4bHG3TvpHFv8d3sPc1T0EEuEKyqM2fJz0LYkrPzV6H9AfbGsTltnzKPiOsQmCZbfR+an",
	"24R365oM3ZlNiwSf4g7JaOfLEV7cL/4dAAD//+vu1uC0OgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
