// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cooldown.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const getCooldown = `-- name: GetCooldown :one
SELECT giver_id, receiver_id, last_hug_at, cooldown_seconds
FROM hug_cooldowns
WHERE giver_id = $1 AND receiver_id = $2
`

type GetCooldownParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) GetCooldown(ctx context.Context, arg GetCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, getCooldown, arg.GiverID, arg.ReceiverID)
	var i HugCooldown
	err := row.Scan(
		&i.GiverID,
		&i.ReceiverID,
		&i.LastHugAt,
		&i.CooldownSeconds,
	)
	return i, err
}

const getOrCreateCooldown = `-- name: GetOrCreateCooldown :one
SELECT giver_id, receiver_id,
       COALESCE(last_hug_at, '1970-01-01 00:00:00+00'::timestamptz) as last_hug_at,
       COALESCE(cooldown_seconds, 3600) as cooldown_seconds
FROM hug_cooldowns
WHERE giver_id = $1 AND receiver_id = $2
LIMIT 1
`

type GetOrCreateCooldownParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) GetOrCreateCooldown(ctx context.Context, arg GetOrCreateCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, getOrCreateCooldown, arg.GiverID, arg.ReceiverID)
	var i HugCooldown
	err := row.Scan(
		&i.GiverID,
		&i.ReceiverID,
		&i.LastHugAt,
		&i.CooldownSeconds,
	)
	return i, err
}

const reduceCooldown = `-- name: ReduceCooldown :one
UPDATE hug_cooldowns
SET cooldown_seconds = GREATEST(cooldown_seconds - $3::int, 300)
WHERE giver_id = $1 AND receiver_id = $2
RETURNING giver_id, receiver_id, last_hug_at, cooldown_seconds
`

type ReduceCooldownParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
	Reduction  int32
}

func (q *Queries) ReduceCooldown(ctx context.Context, arg ReduceCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, reduceCooldown, arg.GiverID, arg.ReceiverID, arg.Reduction)
	var i HugCooldown
	err := row.Scan(
		&i.GiverID,
		&i.ReceiverID,
		&i.LastHugAt,
		&i.CooldownSeconds,
	)
	return i, err
}

const upsertCooldown = `-- name: UpsertCooldown :one
INSERT INTO hug_cooldowns (giver_id, receiver_id, last_hug_at, cooldown_seconds)
VALUES ($1, $2, now(), $3)
ON CONFLICT (giver_id, receiver_id)
DO UPDATE SET last_hug_at = now()
RETURNING giver_id, receiver_id, last_hug_at, cooldown_seconds
`

type UpsertCooldownParams struct {
	GiverID         uuid.UUID
	ReceiverID      uuid.UUID
	CooldownSeconds int32
}

func (q *Queries) UpsertCooldown(ctx context.Context, arg UpsertCooldownParams) (HugCooldown, error) {
	row := q.db.QueryRow(ctx, upsertCooldown, arg.GiverID, arg.ReceiverID, arg.CooldownSeconds)
	var i HugCooldown
	err := row.Scan(
		&i.GiverID,
		&i.ReceiverID,
		&i.LastHugAt,
		&i.CooldownSeconds,
	)
	return i, err
}
