// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hug.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countHugsGiven = `-- name: CountHugsGiven :one
SELECT COUNT(*)
FROM hugs
WHERE giver_id = $1
`

func (q *Queries) CountHugsGiven(ctx context.Context, giverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHugsGiven, giverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHugsReceived = `-- name: CountHugsReceived :one
SELECT COUNT(*)
FROM hugs
WHERE receiver_id = $1
`

func (q *Queries) CountHugsReceived(ctx context.Context, receiverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHugsReceived, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHugByID = `-- name: GetHugByID :one
SELECT id, giver_id, receiver_id, created_at
FROM hugs
WHERE id = $1
`

func (q *Queries) GetHugByID(ctx context.Context, id uuid.UUID) (Hug, error) {
	row := q.db.QueryRow(ctx, getHugByID, id)
	var i Hug
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}

const insertHug = `-- name: InsertHug :one
INSERT INTO hugs (giver_id, receiver_id)
VALUES ($1, $2)
RETURNING id, giver_id, receiver_id, created_at
`

type InsertHugParams struct {
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) InsertHug(ctx context.Context, arg InsertHugParams) (Hug, error) {
	row := q.db.QueryRow(ctx, insertHug, arg.GiverID, arg.ReceiverID)
	var i Hug
	err := row.Scan(
		&i.ID,
		&i.GiverID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}

const listHugsByUser = `-- name: ListHugsByUser :many
SELECT id, giver_id, receiver_id, created_at
FROM hugs
WHERE giver_id = $1 OR receiver_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHugsByUser(ctx context.Context, giverID uuid.UUID) ([]Hug, error) {
	rows, err := q.db.Query(ctx, listHugsByUser, giverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hug
	for rows.Next() {
		var i Hug
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
