// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	UserID    uuid.UUID
	Amount    int32
	UpdatedAt pgtype.Timestamptz
}

type DailyReward struct {
	UserID        uuid.UUID
	LastClaimedAt pgtype.Timestamptz
	StreakDays    int32
}

type Hug struct {
	ID         uuid.UUID
	GiverID    uuid.UUID
	ReceiverID uuid.UUID
	CreatedAt  pgtype.Timestamptz
	Status     string
	AcceptedAt pgtype.Timestamptz
}

type HugCooldown struct {
	UserAID              uuid.UUID
	UserBID              uuid.UUID
	LastHugAt            pgtype.Timestamptz
	CooldownSeconds      int32
	DeclineCooldownUntil pgtype.Timestamptz
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
	Role     string
	Gender   pgtype.Text
	BannedAt pgtype.Timestamptz
}
