// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, role, gender)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, password, role, gender
`

type CreateUserParams struct {
	Username string
	Password string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    u.id,
    u.username,
    u.role,
    u.gender,
    COALESCE(given.cnt, 0) + COALESCE(received.cnt, 0) AS total_hugs,
    COALESCE(given.cnt, 0) AS hugs_given,
    COALESCE(received.cnt, 0) AS hugs_received
FROM users u
LEFT JOIN (
    SELECT giver_id, COUNT(*) AS cnt FROM hugs GROUP BY giver_id
) given ON given.giver_id = u.id
LEFT JOIN (
    SELECT receiver_id, COUNT(*) AS cnt FROM hugs GROUP BY receiver_id
) received ON received.receiver_id = u.id
ORDER BY total_hugs DESC
LIMIT $2::int OFFSET $1::int
`

type GetLeaderboardParams struct {
	Off int32
	Lim int32
}

type GetLeaderboardRow struct {
	ID           uuid.UUID
	Username     string
	Role         string
	Gender       pgtype.Text
	TotalHugs    int32
	HugsGiven    int64
	HugsReceived int64
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.TotalHugs,
			&i.HugsGiven,
			&i.HugsReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentHugsFeed = `-- name: GetRecentHugsFeed :many
SELECT
    h.id,
    h.giver_id,
    h.receiver_id,
    h.created_at,
    g.username AS giver_username,
    r.username AS receiver_username,
    g.gender AS giver_gender
FROM hugs h
JOIN users g ON g.id = h.giver_id
JOIN users r ON r.id = h.receiver_id
ORDER BY h.created_at DESC
LIMIT $1::int
`

type GetRecentHugsFeedRow struct {
	ID               uuid.UUID
	GiverID          uuid.UUID
	ReceiverID       uuid.UUID
	CreatedAt        pgtype.Timestamptz
	GiverUsername    string
	ReceiverUsername string
	GiverGender      pgtype.Text
}

func (q *Queries) GetRecentHugsFeed(ctx context.Context, lim int32) ([]GetRecentHugsFeedRow, error) {
	rows, err := q.db.Query(ctx, getRecentHugsFeed, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentHugsFeedRow
	for rows.Next() {
		var i GetRecentHugsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.CreatedAt,
			&i.GiverUsername,
			&i.ReceiverUsername,
			&i.GiverGender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, role, gender
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, role, gender
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    (SELECT COUNT(*) FROM hugs WHERE hugs.giver_id = $1::uuid)::bigint AS hugs_given,
    (SELECT COUNT(*) FROM hugs WHERE hugs.receiver_id = $1::uuid)::bigint AS hugs_received,
    (SELECT COUNT(*) FROM hugs WHERE hugs.giver_id = $1::uuid)::bigint +
    (SELECT COUNT(*) FROM hugs WHERE hugs.receiver_id = $1::uuid)::bigint AS total_hugs
`

type GetUserStatsRow struct {
	HugsGiven    int64
	HugsReceived int64
	TotalHugs    int32
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.HugsGiven, &i.HugsReceived, &i.TotalHugs)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, role, gender
FROM users
ORDER BY username
LIMIT $2::int OFFSET $1::int
`

type ListAllUsersParams struct {
	Off int32
	Lim int32
}

type ListAllUsersRow struct {
	ID       uuid.UUID
	Username string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, role, gender
FROM users
WHERE username ILIKE '%' || $1::text || '%'
ORDER BY username
LIMIT $3::int OFFSET $2::int
`

type SearchUsersParams struct {
	Query string
	Off   int32
	Lim   int32
}

type SearchUsersRow struct {
	ID       uuid.UUID
	Username string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET gender = $2
WHERE id = $1
RETURNING id, username, password, role, gender
`

type UpdateUserSettingsParams struct {
	ID     uuid.UUID
	Gender pgtype.Text
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings, arg.ID, arg.Gender)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
	)
	return i, err
}
