// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateGender = `-- name: AdminUpdateGender :one
UPDATE users
SET gender = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots
`

type AdminUpdateGenderParams struct {
	ID     uuid.UUID
	Gender pgtype.Text
}

func (q *Queries) AdminUpdateGender(ctx context.Context, arg AdminUpdateGenderParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateGender, arg.ID, arg.Gender)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const adminUpdatePassword = `-- name: AdminUpdatePassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type AdminUpdatePasswordParams struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) AdminUpdatePassword(ctx context.Context, arg AdminUpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, adminUpdatePassword, arg.ID, arg.Password)
	return err
}

const adminUpdateUsername = `-- name: AdminUpdateUsername :one
UPDATE users
SET username = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots
`

type AdminUpdateUsernameParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) AdminUpdateUsername(ctx context.Context, arg AdminUpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const banUser = `-- name: BanUser :one
UPDATE users
SET banned_at = NOW()
WHERE id = $1 AND role != 'admin'
RETURNING id, username, password, role, gender, banned_at, hug_slots
`

func (q *Queries) BanUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, banUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const countBannedUsers = `-- name: CountBannedUsers :one
SELECT COUNT(*) FROM users WHERE banned_at IS NOT NULL
`

func (q *Queries) CountBannedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBannedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, role, gender)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, password, role, gender, banned_at, hug_slots
`

type CreateUserParams struct {
	Username string
	Password string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    u.id,
    u.username,
    u.role,
    u.gender,
    COALESCE(given.cnt, 0) + COALESCE(received.cnt, 0) AS total_hugs,
    COALESCE(given.cnt, 0) AS hugs_given,
    COALESCE(received.cnt, 0) AS hugs_received
FROM users u
LEFT JOIN (
    SELECT giver_id, COUNT(*) AS cnt FROM hugs WHERE status = 'completed' GROUP BY giver_id
) given ON given.giver_id = u.id
LEFT JOIN (
    SELECT receiver_id, COUNT(*) AS cnt FROM hugs WHERE status = 'completed' GROUP BY receiver_id
) received ON received.receiver_id = u.id
ORDER BY total_hugs DESC
LIMIT $2::int OFFSET $1::int
`

type GetLeaderboardParams struct {
	Off int32
	Lim int32
}

type GetLeaderboardRow struct {
	ID           uuid.UUID
	Username     string
	Role         string
	Gender       pgtype.Text
	TotalHugs    int32
	HugsGiven    int64
	HugsReceived int64
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.TotalHugs,
			&i.HugsGiven,
			&i.HugsReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentHugsFeed = `-- name: GetRecentHugsFeed :many
SELECT
    h.id,
    h.giver_id,
    h.receiver_id,
    h.created_at,
    g.username AS giver_username,
    r.username AS receiver_username,
    g.gender AS giver_gender
FROM hugs h
JOIN users g ON g.id = h.giver_id
JOIN users r ON r.id = h.receiver_id
WHERE h.status = 'completed'
ORDER BY h.created_at DESC
LIMIT $1::int
`

type GetRecentHugsFeedRow struct {
	ID               uuid.UUID
	GiverID          uuid.UUID
	ReceiverID       uuid.UUID
	CreatedAt        pgtype.Timestamptz
	GiverUsername    string
	ReceiverUsername string
	GiverGender      pgtype.Text
}

func (q *Queries) GetRecentHugsFeed(ctx context.Context, lim int32) ([]GetRecentHugsFeedRow, error) {
	rows, err := q.db.Query(ctx, getRecentHugsFeed, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentHugsFeedRow
	for rows.Next() {
		var i GetRecentHugsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.GiverID,
			&i.ReceiverID,
			&i.CreatedAt,
			&i.GiverUsername,
			&i.ReceiverUsername,
			&i.GiverGender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, role, gender, banned_at, hug_slots
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, role, gender, banned_at, hug_slots
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const getUserSlots = `-- name: GetUserSlots :one
SELECT hug_slots FROM users WHERE id = $1
`

func (q *Queries) GetUserSlots(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserSlots, id)
	var hug_slots int32
	err := row.Scan(&hug_slots)
	return hug_slots, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*) FILTER (WHERE giver_id = $1::uuid)::bigint AS hugs_given,
    COUNT(*) FILTER (WHERE receiver_id = $1::uuid)::bigint AS hugs_received,
    COUNT(*)::bigint AS total_hugs
FROM hugs
WHERE (giver_id = $1::uuid OR receiver_id = $1::uuid)
  AND status = 'completed'
`

type GetUserStatsRow struct {
	HugsGiven    int64
	HugsReceived int64
	TotalHugs    int64
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.HugsGiven, &i.HugsReceived, &i.TotalHugs)
	return i, err
}

const incrementUserSlots = `-- name: IncrementUserSlots :one
UPDATE users
SET hug_slots = hug_slots + 1
WHERE id = $1 AND hug_slots < 5
RETURNING hug_slots
`

func (q *Queries) IncrementUserSlots(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUserSlots, id)
	var hug_slots int32
	err := row.Scan(&hug_slots)
	return hug_slots, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, role, gender
FROM users
WHERE banned_at IS NULL
  AND id NOT IN (
    SELECT blocked_id FROM user_blocks WHERE blocker_id = $1::uuid
    UNION
    SELECT blocker_id FROM user_blocks WHERE blocked_id = $1::uuid
  )
ORDER BY username
LIMIT $3::int OFFSET $2::int
`

type ListAllUsersParams struct {
	ViewerID uuid.UUID
	Off      int32
	Lim      int32
}

type ListAllUsersRow struct {
	ID       uuid.UUID
	Username string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT u.id, u.username, u.role, u.gender, u.banned_at,
       COALESCE(b.amount, 0)::int AS balance
FROM users u
LEFT JOIN balances b ON b.user_id = u.id
ORDER BY u.username
LIMIT $2::int OFFSET $1::int
`

type ListUsersAdminParams struct {
	Off int32
	Lim int32
}

type ListUsersAdminRow struct {
	ID       uuid.UUID
	Username string
	Role     string
	Gender   pgtype.Text
	BannedAt pgtype.Timestamptz
	Balance  int32
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
			&i.BannedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, role, gender
FROM users
WHERE username ILIKE '%' || $1::text || '%'
  AND banned_at IS NULL
  AND id NOT IN (
    SELECT blocked_id FROM user_blocks WHERE blocker_id = $2::uuid
    UNION
    SELECT blocker_id FROM user_blocks WHERE blocked_id = $2::uuid
  )
ORDER BY username
LIMIT $4::int OFFSET $3::int
`

type SearchUsersParams struct {
	Query    string
	ViewerID uuid.UUID
	Off      int32
	Lim      int32
}

type SearchUsersRow struct {
	ID       uuid.UUID
	Username string
	Role     string
	Gender   pgtype.Text
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Query,
		arg.ViewerID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :one
UPDATE users
SET banned_at = NULL
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots
`

func (q *Queries) UnbanUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, unbanUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET gender = $2
WHERE id = $1
RETURNING id, username, password, role, gender, banned_at, hug_slots
`

type UpdateUserSettingsParams struct {
	ID     uuid.UUID
	Gender pgtype.Text
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings, arg.ID, arg.Gender)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Gender,
		&i.BannedAt,
		&i.HugSlots,
	)
	return i, err
}
